// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    description: "Cracking the Coding Interview, 6th Edition is here to help you through this process, teaching you what you need to know and enabling you to perform at your very best. I've coached and interviewed hundreds of software engineers. The result is this book.Learn how to uncover the hints and hidden details in a question, discover how to break down a problem into manageable chunks, develop techniques to unstick yourself when stuck, learn (or re-learn) core computer science concepts, and practice on 189 interview questions and solutions. These interview questions are real; they are not pulled out of computer science textbooks. They reflect what’s truly being asked at the top companies, so that you can be as prepared as possible.",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
    description: "In this ground-breaking book, Clear reveals exactly how these minuscule changes can grow into such life-altering outcomes. He uncovers a handful of simple life hacks (the forgotten art of Habit Stacking, the unexpected power of the Two Minute Rule, or the trick to entering the Goldilocks Zone) and delves into cutting-edge psychology and neuroscience to explain why they matter. Along the way, he tells inspiring stories of Olympic gold medalists, leading CEOs and distinguished scientists who have used the science of tiny habits to stay productive, motivated, and happy.",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
    description: "In Can't Hurt Me, Goggins shares his astonishing life story and reveals that most of us tap into only 40 percent of our capabilities. Goggins calls this The 40% Rule, and his story illuminates a path that anyone can follow to push past pain, demolish fear, and reach their full potential. An annotated edition of Can't Hurt Me, offering over two hours of bonus content featuring deeper insights and never-before-told stories shared by David.",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
    description: "Many modern knowledge workers now spend most of their brain power battling distraction and interruption, whether because of the incessant pinging of devices, noisy open-plan offices or the difficulty of deciding what deserves their attention the most. When Cal Newport coined the term deep work on his popular blog, Study Hacks, in 2012, he found the concept quickly hit a nerve. Most of us, after all, are excruciatingly familiar with shallow work instead - distractedly skimming the surface of our workload and never getting to the important part. Newport began exploring the methods and mind-set that foster a practice of distraction-free productivity at work, and now, in Deep Work, he shows how anyone can achieve this elusive state.",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
    description:"With The 10X Rule , you'll learn to establish the amount of effort needed to guarantee success and ensure that you can continue operating at this level throughout your life. Most people desire success and have great ideas but they come up short on the amount of action required to get their lives to the exceptional levels they deserve. Four degrees of action exist, and in order to achieve your dreams, you must learn to operate at the fourth degree of action: Massive Action. The 10X Rule will dissolve fear, increase your belief in yourself, eliminate procrastination, and provide you with an overwhelming sense of purpose. The 10X Rule compels you to separate yourself from everyone else in the market—and you do that by doing what others refuse to do. Stop thinking in terms of basic needs, and start aiming for abundance—in all areas of your life. The 10X Rule guides you toward the frame of mind that all successful people share. Aim ten times higher than you are right now—and if you come up short, you'll still find yourself further along than if you had maintained your life's current status quo.",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
    description:"Whether it's selling your company's product in the boardroom or selling yourself on eating healthy, everything in life can and should be treated as a sale. And as sales expert Grant Cardone explains, knowing the principles of selling is a prerequisite for success of any kind. In Sell or Be Sold, Cardone breaks down the techniques and approaches necessary to master the art of selling in any avenue. You will learn how to handle rejection, turn around negative situations, shorten sales cycles, and guarantee yourself greatness.",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 3.5,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
    description: "Rich Dad Poor Dad is Robert's story of growing up with two dads - his real father and the father of his best friend, his rich dad - and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
    description:"Robert believes that the reason most people struggle financially is because they've spent years in school but were never taught about money. Robert’s rich dad taught him that this lack of financial education is why so many people work so hard all their lives for money...instead of learning how to make money work for them.",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
    description:"Amoral, cunning, ruthless, and instructive, this piercing work distills 3,000 years of the history of power into 48 well-explicated laws. This bold volume outlines the laws of power in their unvarnished essence, synthesizing the philosophies of Machiavelli, Sun Tzu, Carl von Clausewitz, and other infamous strategists. The 48 Laws of Power will fascinate any listener interested in gaining, observing, or defending against ultimate control.",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
    description:"Throughout your life, you've had parents, coaches, teachers, friends, and mentors who have pushed you to be better than your excuses and bigger than your fears. What if the secret to having the confidence and courage to enrich your life and work is simply knowing how to push yourself? Using the science of habits, riveting stories, and surprising facts from some of the most famous moments in history, art, and business, Mel Robbins will explain the power of a 'push moment'. Then, she'll give you one simple tool you can use to become your greatest self.",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
    description:"Dale Carnegie could never have predicted the trajectory that new media would take, and the ways that the simple television screen would be adapted into computers and handheld communication devices. He didn’t know the term “social media” and Facebook was something not even dreamed of in Buck Rogers cartoons. And yet his lessons remain relevant for everyone who communicates online today. In fact, with problems such as cyber bullying and email etiquette, we need Carnegie’s help more than ever. Dale Carnegie and Associates, Inc. has re-imagined Carnegie’s lasting lessons for this difficult digital age, reframing Carnegie’s insights about communication, self-expression, and leadership. This book is a must-have guide for anyone who wants to find success on Facebook, Linked-In, Twitter, and any social media format today and in the future.",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    description:"Told through Robert Greene's signature blend of historical anecdote and psychological insight and drawing on interviews with world leaders, Mastery builds on the strategies outlined in The 48 Laws of Power to provide a practical guide to greatness - and how to start living by your own rules.",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];